FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json /app/frontend/
RUN cd frontend && npm install
COPY frontend /app/frontend
RUN cd frontend && npm run build
FROM node:20-alpine
WORKDIR /app/frontend
COPY --from=build /app/frontend .
CMD ["npm","run","dev","--","--host","0.0.0.0"]
